name: Build Python PDFMiner project

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
  lint:
    needs: install
    steps:
      - name: Lint with flake8
        run: |
          flake8 .
  test:
    needs: install
    steps:
      - name: Test code
        run: |
          make test